name: MarsFormat Test Workflow

on:
  # Trigger the workflow on push to devel branch
  push:
    branches: [ devel ]
    paths:
      - 'bin/MarsFormat.py'
      - 'tests/test_marsformat.py'
      - '.github/workflows/marsformat_test.yml'
  # Allow manual triggering of the workflow
  workflow_dispatch:
  # Trigger on pull requests that modify MarsFormat or tests
  pull_request:
    branches: [ devel ]
    paths:
      - 'bin/MarsFormat.py'
      - 'tests/test_marsformat.py'
      - '.github/workflows/marsformat_test.yml'

jobs:
  test:
    # Run on multiple OS and Python versions for comprehensive testing
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.11']
    
    runs-on: ${{ matrix.os }}
    
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
      
      # Set up the specified Python version
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      
      # Install dependencies
      - name: Install dependencies
        shell: bash  
        run: |
          python -m pip install --upgrade pip
          pip install numpy xarray netCDF4 matplotlib scipy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      # Install the package in editable mode
      - name: Install package
        run: pip install -e .
      
      # Set HOME for Windows since it might be used by the script
      - name: Set HOME environment variable for Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          echo "HOME=$env:USERPROFILE" >> $env:GITHUB_ENV
      
      # Set up AmesCAP configuration - handle platform differences
      - name: Set up AmesCAP configuration
        shell: bash
        run: |
          mkdir -p $HOME/.amescap
          cp mars_templates/amescap_profile $HOME/.amescap_profile
    
      # Print out environment info
      - name: Show environment info
        run: |
          python -c "import os, sys, numpy, netCDF4, xarray; print(f'Python: {sys.version}, NumPy: {numpy.__version__}, NetCDF4: {netCDF4.__version__}, xarray: {xarray.__version__}')"
          echo "Working directory: $(pwd)"
          echo "Home directory: $HOME"
          echo "Environment variables: $(env)"
            
      # Run the tests
      - name: Run MarsFormat tests
        run: python -m unittest -v tests/test_marsformat.py