name: MarsPull CI

on:
  push:
    branches: [ main, master ]
    paths:
      - 'bin/MarsPull.py'
      - 'tests/test_marspull.py'
      - '.github/workflows/marspull.yml'
      - 'pyproject.toml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'bin/MarsPull.py'
      - 'tests/test_marspull.py'
      - '.github/workflows/marspull.yml'
      - 'pyproject.toml'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install pytest
        pip install flake8
        pip install .
    
    - name: Run unit tests
      run: |
        python -m unittest tests/test_marspull.py
    
    - name: Check Linting
      run: |
        flake8 bin/MarsPull.py tests/test_marspull.py --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 bin/MarsPull.py tests/test_marspull.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Build Package
      run: |
        python -m build