name: Test MarsPull

on:
  push:
    branches: [ devel ]
    # paths:
    #   - 'bin/MarsPull'
    #   - 'bin/MarsPull.py'
    #   - 'amescap/**'
    #   - 'tests/test_marspull.py'
  pull_request:
    branches: [ devel ]
    # paths:
    #   - 'bin/MarsPull'
    #   - 'bin/MarsPull.py'
    #   - 'amescap/**'
    #   - 'tests/test_marspull.py'
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Create virtual environment
      run: |
        python -m venv amescap
        source amescap/bin/activate
        python -m pip install --upgrade pip
    
    - name: Install AmesCAP dependencies
      run: |
        source amescap/bin/activate
        # Install all required dependencies
        pip install numpy requests unittest-mock pytest matplotlib scipy xarray netCDF4
    
    - name: Install AmesCAP from GitHub
      run: |
        source amescap/bin/activate
        # Check Python version
        python --version
        
        # Clone the repository
        git clone --branch devel https://github.com/falconstryker/AmesCAP.git
        cd AmesCAP
        
        # Install in development mode
        pip install -e .
        
        # Check if installation was successful
        pip list | grep amescap
        
        # Copy profile file if it exists
        if [ -f mars_templates/amescap_profile ]; then
          cp mars_templates/amescap_profile ~/.amescap_profile
        elif [ -f mars_templates/amescap-profile ]; then
          cp mars_templates/amescap-profile ~/.amescap_profile
        else
          echo "Profile file not found in expected location."
        fi
        
        cd ..
    
    - name: Test MarsPull help message
      run: |
        source amescap/bin/activate
        MarsPull -h
    
    - name: Test MarsPull list functionality
      run: |
        source amescap/bin/activate
        MarsPull -list || echo "List command may require internet access or specific permissions"
    
    - name: Create simple test script
      run: |
        mkdir -p tests
        cat > tests/test_marspull.py << EOF
        import unittest
        import subprocess
        import os
        import sys

        class TestMarsPull(unittest.TestCase):
            def test_help_command(self):
                result = subprocess.run(["MarsPull", "-h"], capture_output=True, text=True)
                self.assertEqual(result.returncode, 0)
                self.assertIn("Uility for downloading NASA Ames Mars Global Climate", result.stdout)
            
            def test_list_command(self):
                result = subprocess.run(["MarsPull", "-list"], capture_output=True, text=True)
                if result.returncode == 0:
                    self.assertIn("Available", result.stdout)
            
            def test_error_on_missing_args(self):
                result = subprocess.run(["MarsPull", "ACTIVECLDS"], capture_output=True, text=True)
                self.assertIn("ERROR No file requested", result.stdout)

        if __name__ == '__main__':
            unittest.main()
        EOF
    
    - name: Run tests
      run: |
        source amescap/bin/activate
        # Make sure MarsPull is available
        which MarsPull || echo "MarsPull not found in PATH"
        python -m unittest -v tests/test_marspull.py
    
    - name: Check for package integrity
      run: |
        source amescap/bin/activate
        # Print Python path to debug
        echo "Python path:"
        python -c "import sys; print(sys.path)"
        
        # Check installed packages
        pip list
        
        # Check if other expected scripts are installed
        if command -v MarsPlot &> /dev/null; then
          echo "MarsPlot is installed and working"
          MarsPlot -h
        else
          echo "MarsPlot not found, installation may be incomplete"
          echo "Checking for script locations:"
          find amescap -name "MarsPull.py" -o -name "MarsPlot.py"
          find AmesCAP -name "MarsPull.py" -o -name "MarsPlot.py" 2>/dev/null || echo "AmesCAP directory not found"
        fi
        
    - name: Upload test artifacts on failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: test-output
        path: |
          tests/*
          ~/.amescap_profile